SRC = ../src
PROGRAMS := $(patsubst $(SRC)/%.cpp,%,$(wildcard $(SRC)/*.cpp)) 
PROGRAMS := $(filter-out main,$(PROGRAM))

all:
	$(MAKE) -C ..

clean:
	$(MAKE) -C .. clean

$(PROGRAMS): %:
	$(MAKE) -C .. $@
